### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by kskenyon** [reloxx13/SonWEB#16] opened 2018-01-27 22:51 UTC
Minimal Firmware: DEVICE_UPDATE_UPLAOD_FIRMWARE_MIN_WRONG_FORMAT!
Full Firmware: Wrong Format! Please upload Full Firmware BIN file!!

I even get this with firmware downloads directly from the GitHub site.

**Comment by kskenyon** [comment] 2018-01-27 23:01
Friendly names are not showing up for each device:

ID | Name | IP | State |   | Version | Runtime | Add device
-- | -- | -- | -- | -- | -- | -- | --
1 | SonoffPOW | 10.0.1.101 |   | 100% | 5.11.1f | ~3h |  
2 |                     | 10.0.1.103 |   | 100% | 5.11.1f | ~22h |  
3 |                     | 10.0.1.105 |   | 100% | 5.11.1f | ~22h |  
4 | electro2 1  | 10.0.1.106 |   | 100% | 5.11.1f | ~22h |  
4 | electro2 2 | 10.0.1.106 |   | 100% | 5.11.1f | ~22h |  
5 |                     | 10.0.1.117 |   | 100% | 5.11.1f | ~22h |  
6 |                     | 10.0.1.121 |   | 100% | 5.11.1f | ~4h |  
7 | SonoffTH10 | 10.0.1.129 |   | 94% | 5.11.1f | ~3h |

**Comment by reloxx13** [comment] 2018-01-30 00:17
Heya,

i cannot reproduce this.
Seems like the webserver is misconfigured.
those are not friendly names on the device list, those are names you gave the devices when you add them to sonweb. if they are missing, it could not save into the device.csv file in the data folder.

please be sure to set write rights for the apache/nginx (?) user.

seems also that the uploaded file could not be saved on the webserver. they are saved first in the php tmp folder and after uploading they get moved to the data/firmwares folder.

if you use apache, please create a own vhost config and put sonweb it the document root you defined in the vhost config without subfolder. their bust be a /var/www/sonweb/index.php (and teh other sonweb files in here).

i also got some reports from users with raspberrys, seems like raspberry is a lil bit harder to config the correct rights for the webserver. 

you could try this on raspberry:
sudo chown www-data:www-data /var/www
sudo chmod 775 /var/www
#add pi user to www-data
sudo usermod -a -G www-data pi
sudo reboot

i hope you can find the problem with this infos :S

**Comment by kskenyon** [comment] 2018-01-30 00:58
Thanks, I got the permissions sorted but this is still happening.  I use Atom on a Mac to build the firmware and it looks like SonWEB doesn’t like the mime type on a Mac.  SonWEB is running on Fedora 27 with apache. I could build on Linux but this will still be a problem for other users who build on a Mac.

Minimal Firmware: Wrong Format! Please upload Minimal Firmware BIN file! application/macbinary!
Full Firmware: Wrong Format! Please upload Full Firmware BIN file! application/macbinary!

I really like what you have developed.  Nice work.

Kevin

**Comment by reloxx13** [comment] 2018-01-30 09:51
Heya, 

thank for the response :)

you are right, its "application/macbinary" 👍 
ill fix it asap

**Comment by reloxx13** [comment] 2018-01-30 10:34
fixed

**Comment by kskenyon** [comment] 2018-01-30 14:05
That’s fixed!  Thanks.

SelfUpdate didn’t work right.  It said the SonWEB update was applied but it didn’t work.  I restarted Apache and it still didn’t work.  It finally worked when I did a git pull to my SonWEB directory directly.  Check your selfupdate code again.  I thought I had all the permissions right and there was no warning of a problem with the selfupdate.

Another question, can I use mdns/Avahi (name.local) URL instead of IP since my Sonoffs are all connected with DHCP?  I haven’t had luck when I tried it.  5.11.1f
My IP’s sometimes change.  

Kevin

**Comment by reloxx13** [comment] 2018-01-30 19:08
Hmm i tried it and it works :S

![grafik](https://user-images.githubusercontent.com/14855001/35585865-66358686-05f9-11e8-8d5f-571dcb0b47ba.png)

**Comment by reloxx13** [comment] 2018-01-30 19:37
> SelfUpdate didn’t work right. It said the SonWEB update was applied but it didn’t work. I restarted Apache and it still didn’t work. It finally worked when I did a git pull to my SonWEB directory directly. Check your selfupdate code again. I thought I had all the permissions right and there was no warning of a problem with the selfupdate.

Thanks for this note, i found a bug their and fixed it.

Its neccessery now to do the next self update 2 times.

1st time fix the bug
2nd correct copy of the update

**Comment by kskenyon** [comment] 2018-01-30 19:57
Thanks, it looks like mdns stopped working with Tasmota for some reason.  Not your problem.  Another puzzle.

Just noticed the red outline on the light bulb when communication fails.  Nice idea!

Thanks for the quick updates.  I really appreciate it.

Kevin
In Indiana

**Comment by kskenyon** [comment] 2018-01-30 20:19
PS, Fehler hasn’t been translated to EN on the Devices page.  There are a few other places DE is showing up.  I needed to learn German anyway.

The selfupdate seems to be working now.

Kevin

**Comment by reloxx13** [comment] 2018-01-30 20:26
Heya,

yup, those are javascript outputs and on my todo.
https://github.com/reloxx13/SonWEB/issues/22#issuecomment-361641986

**Comment by reloxx13** [comment] 2018-01-30 23:03
i added js transation.

ill close this here.

if you have anotehr issue, just open a new ticket 👍 

Thanks for all your feedback :)

**Closed by reloxx13** 2018-01-30 23:03 UTC
Labels: QUESTION
